# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Any, Iterable, Mapping

import pandas as pd

from .condition_fit import evaluate_condition_fit
from .horse_trust import build_horse_trust_materials, rows_by_horse_number
from .purchase_conditions import clean_text, horse_no, to_float
from .ticket_strategy_analysis import unique_nums


POSITIVE_STRAIGHT_WORDS = (
    "勝ち負け",
    "押切",
    "差切",
    "末脚",
    "伸びる",
    "浮上",
    "直線勝負",
)
POSITIVE_CORNER_WORDS = ("先頭", "好位", "進出", "押し上げ", "中団")
PACE_SUPPORT_WORDS = ("展開向く", "展開有利", "展開材料", "単騎", "前残り", "楽逃げ", "好位")
FRONT_STYLE_WORDS = ("逃", "先")
UP_TREND_WORDS = ("上昇", "良化", "持ち直し", "反発", "安定")
DOWN_TREND_WORDS = ("下降", "急落", "不安")


def build_final_betting_context(
    table: Any,
    race_type: str = "jra",
    *,
    ticket_numbers: Iterable[Any] | None = None,
    race_info: Mapping[str, Any] | None = None,
) -> tuple[dict[str, Any], ...]:
    """Collect current-race judgement materials without changing predictions.

    This is an audit/display layer only.  It reads existing columns generated by
    the prediction flow and does not recalculate AI scores, marks, groups,
    ability values, pace, or tickets.
    """

    if table is None or not isinstance(table, pd.DataFrame) or table.empty:
        return ()
    wanted = set(_unique_numbers(ticket_numbers or []))
    by_no = rows_by_horse_number(table)
    contexts: list[dict[str, Any]] = []
    for number in sorted(by_no, key=lambda value: int(value) if str(value).isdigit() else 999):
        if wanted and number not in wanted:
            continue
        row = by_no[number]
        contexts.append(_context_for_row(row, race_type, race_info))
    return tuple(contexts)


def build_ticket_alignment(
    contexts: Iterable[Mapping[str, Any]],
    tickets: Iterable[Iterable[Any]],
    *,
    strategy_id: str = "",
    strategy_label: str = "",
) -> tuple[dict[str, Any], ...]:
    by_no = {clean_text(item.get("horse_number")): item for item in contexts if clean_text(item.get("horse_number"))}
    rows: list[dict[str, Any]] = []
    for ticket in tickets:
        numbers = _unique_numbers(ticket)
        if not numbers:
            continue
        matched: list[str] = []
        unmatched: list[str] = []
        partial: list[str] = []
        horse_contexts: list[Mapping[str, Any]] = []
        for number in numbers:
            context = by_no.get(number)
            if context is None:
                unmatched.append(f"{number}は今回評価なし")
                continue
            horse_contexts.append(context)
            status, reason = _horse_alignment_status(context)
            if status == "strong":
                matched.append(reason)
            elif status == "medium":
                partial.append(reason)
            else:
                unmatched.append(reason)

        if horse_contexts and not unmatched and matched:
            alignment = "一致"
            reason = " / ".join(matched + partial)
            mismatch_reason = ""
        elif horse_contexts and (matched or partial):
            alignment = "一部一致"
            reason = " / ".join(matched + partial)
            mismatch_reason = " / ".join(unmatched)
        else:
            alignment = "不一致"
            reason = ""
            mismatch_reason = " / ".join(unmatched) or "今回評価の構造化データが不足"

        rows.append(
            {
                "strategy_id": strategy_id,
                "strategy_label": strategy_label,
                "ticket": "-".join(numbers),
                "horse_numbers": numbers,
                "alignment": alignment,
                "alignment_reason": reason or mismatch_reason,
                "matched_reasons": matched,
                "partial_reasons": partial,
                "unmatched_reasons": unmatched,
                "horse_contexts": horse_contexts,
            }
        )
    return tuple(rows)


def context_summary_lines(contexts: Iterable[Mapping[str, Any]]) -> tuple[str, ...]:
    lines: list[str] = []
    for context in contexts:
        lines.extend(_summary_lines_for_context(context))
    return tuple(lines)


def ticket_alignment_lines(rows: Iterable[Mapping[str, Any]]) -> tuple[str, ...]:
    out: list[str] = []
    mark = {"一致": "○", "一部一致": "△", "不一致": "×"}
    for row in rows:
        ticket = clean_text(row.get("ticket"))
        alignment = clean_text(row.get("alignment")) or "不一致"
        reason = clean_text(row.get("alignment_reason"))
        out.append(f"{ticket} {mark.get(alignment, '×')} {alignment}" + (f"：{reason}" if reason else ""))
    return tuple(out)


def _context_for_row(
    row: Mapping[str, Any],
    race_type: str,
    race_info: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    number = horse_no(_pick(row, "horse_no_eval", "馬番", "horse_no", "horse_number", "馬"))
    ability = _number(row, "能力評価値", "ability_display_score", "raw_score", "_raw_score")
    gauge = _gauge_from_existing_ability(ability)
    trend = _pick(row, "近3走傾向", "recent3_trend", "勢い")
    trend_label = _trend_label(row, trend)
    corner = _pick(row, "4角予想", "4角評価", "corner4_evaluation")
    straight = _pick(row, "直線評価", "straight_evaluation")
    pace_fit = _pick(row, "展開タイプ", "展開印", "展開コメント", "pace_fit", "展開補正")
    running_style = _pick(row, "脚質", "running_style", "style")
    start_group = _start_group_from_style(running_style)
    trust_materials = build_horse_trust_materials(row, race_type)
    condition_fit = evaluate_condition_fit(row, race_info)
    return {
        "horse_number": number,
        "horse_name": _pick(row, "horse_name_eval", "馬名", "horse_name", "name"),
        "base": {
            "mark": _pick(row, "mark_eval", "表示印", "display_mark", "最終印", "印", "mark"),
            "group": _pick(row, "display_group_eval", "グループ", "display_group"),
            "ai_score": _pick(row, "ai_score_eval", "AI点", "normalized_ai_score", "ai_score"),
            "ai_rank": _pick(row, "ai_rank_eval", "AI順位", "ai_rank"),
            "ability": ability,
        },
        "trust": {
            item.get("key"): {
                "display": item.get("display"),
                "grade": item.get("grade"),
                "detail": item.get("detail"),
                "source_columns": item.get("source_columns"),
            }
            for item in trust_materials
            if item.get("key")
        },
        "trust_summary": " / ".join(item["display"] for item in trust_materials[:5] if clean_text(item.get("display"))),
        "condition_fit": {
            "mark": condition_fit.get("condition_fit_mark"),
            "level": condition_fit.get("condition_fit_level"),
            "label": condition_fit.get("condition_fit_label"),
            "reason": condition_fit.get("condition_fit_reason"),
            "matched_past_runs": condition_fit.get("matched_past_runs", []),
        },
        "momentum": {
            "gauge": gauge,
            "gauge_source": "能力評価値" if ability is not None else None,
            "trend": _none_if_empty(trend),
            "trend_label": _none_if_empty(trend_label),
            "momentum_rank": _none_if_empty(_pick(row, "勢いランク", "momentum_rank")),
            "momentum_score": _pick(row, "勢いスコア", "momentum_score"),
        },
        "race_shape": {
            "start_evaluation": start_group,
            "start_rank": _pick(row, "スタート順位", "start_rank"),
            "corner4_evaluation": _none_if_empty(corner),
            "corner4_rank": _pick(row, "4角順位", "corner4_rank"),
            "straight_evaluation": _none_if_empty(straight),
            "straight_rank": _pick(row, "直線順位", "straight_rank"),
            "pace_fit": _none_if_empty(pace_fit),
            "front_survival_flag": _front_survival_flag(running_style, pace_fit, corner, straight),
            "race_comment_role": _race_comment_role(row, start_group, corner, straight, pace_fit),
        },
        "bet_strategy": {
            "candidate_ticket": None,
            "strategy_score": None,
            "expected_roi": None,
            "robustness": None,
            "historical_samples": None,
        },
        "display_summary": _display_summary(number, row, trust_materials, gauge, trend_label, corner, straight, condition_fit),
    }


def _horse_alignment_status(context: Mapping[str, Any]) -> tuple[str, str]:
    base = context.get("base") if isinstance(context.get("base"), Mapping) else {}
    momentum = context.get("momentum") if isinstance(context.get("momentum"), Mapping) else {}
    shape = context.get("race_shape") if isinstance(context.get("race_shape"), Mapping) else {}
    number = clean_text(context.get("horse_number"))
    name = clean_text(context.get("horse_name"))
    label = " ".join(part for part in [number, name] if part)

    group = clean_text(base.get("group"))
    mark = clean_text(base.get("mark"))
    gauge = to_float(momentum.get("gauge"))
    straight = clean_text(shape.get("straight_evaluation"))
    corner = clean_text(shape.get("corner4_evaluation"))
    pace = clean_text(shape.get("pace_fit"))
    trend = clean_text(momentum.get("trend_label") or momentum.get("trend"))

    strong_bits: list[str] = []
    if group in {"SS", "A"}:
        strong_bits.append(f"勢力図{group}")
    if mark in {"◎", "○", "▲"}:
        strong_bits.append(f"印{mark}")
    if gauge is not None and gauge >= 80:
        strong_bits.append(f"ゲージ{int(gauge)}")
    if _contains_any(straight, POSITIVE_STRAIGHT_WORDS):
        strong_bits.append(f"直線{straight}")

    medium_bits: list[str] = []
    if group in {"B", "C"}:
        medium_bits.append(f"勢力図{group}")
    if gauge is not None and 65 <= gauge < 80:
        medium_bits.append(f"ゲージ{int(gauge)}")
    if _contains_any(corner, POSITIVE_CORNER_WORDS):
        medium_bits.append(f"4角{corner}")
    if _contains_any(pace, PACE_SUPPORT_WORDS):
        medium_bits.append("展開材料あり")
    if _contains_any(trend, UP_TREND_WORDS):
        medium_bits.append(f"状態{trend}")

    if strong_bits:
        return "strong", f"{label}は" + "・".join(strong_bits)
    if medium_bits:
        return "medium", f"{label}は" + "・".join(medium_bits)
    weak_parts = [part for part in [f"勢力図{group}" if group else "", f"直線{straight}" if straight else "直線評価なし"] if part]
    return "weak", f"{label}は" + "・".join(weak_parts)


def _summary_lines_for_context(context: Mapping[str, Any]) -> list[str]:
    base = context.get("base") if isinstance(context.get("base"), Mapping) else {}
    momentum = context.get("momentum") if isinstance(context.get("momentum"), Mapping) else {}
    shape = context.get("race_shape") if isinstance(context.get("race_shape"), Mapping) else {}
    condition_fit = context.get("condition_fit") if isinstance(context.get("condition_fit"), Mapping) else {}
    header = " ".join(
        part
        for part in [
            clean_text(base.get("mark")),
            clean_text(context.get("horse_number")),
            clean_text(context.get("horse_name")),
        ]
        if part
    )
    trust = clean_text(context.get("trust_summary"))
    gauge = momentum.get("gauge")
    trend = _trend_display(momentum.get("trend_label") or momentum.get("trend"))
    shape_line = " / ".join(
        part
        for part in [
            f"4角 {shape.get('corner4_rank')}位" if shape.get("corner4_rank") not in (None, "") else (f"4角 {shape.get('corner4_evaluation')}" if shape.get("corner4_evaluation") else ""),
            f"直線 {shape.get('straight_rank')}位" if shape.get("straight_rank") not in (None, "") else (f"直線 {shape.get('straight_evaluation')}" if shape.get("straight_evaluation") else ""),
        ]
        if clean_text(part)
    )
    lines = [header]
    if trust:
        lines.append(trust)
    condition_label = _condition_fit_display(condition_fit)
    if condition_label:
        lines.append(condition_label)
    lines.append(" / ".join(part for part in [f"ゲージ {gauge}" if gauge is not None else "", trend] if clean_text(part)))
    if shape_line:
        lines.append(shape_line)
    return [line for line in lines if clean_text(line)]


def _display_summary(
    number: str,
    row: Mapping[str, Any],
    materials: list[dict[str, Any]],
    gauge: int | None,
    trend: Any,
    corner: Any,
    straight: Any,
    condition_fit: Mapping[str, Any] | None = None,
) -> str:
    header = " ".join(part for part in [_pick(row, "表示印", "mark_eval", "mark"), number, _pick(row, "馬名", "horse_name_eval")] if clean_text(part))
    trust = " / ".join(item["display"] for item in materials[:5] if clean_text(item.get("display")))
    momentum = " / ".join(part for part in [f"ゲージ {gauge}" if gauge is not None else "", _trend_display(trend)] if clean_text(part))
    shape = " / ".join(part for part in [f"4角 {clean_text(corner)}" if clean_text(corner) else "", f"直線 {clean_text(straight)}" if clean_text(straight) else ""] if part)
    condition = _condition_fit_display(condition_fit or {})
    return "\n".join(line for line in [header, trust, condition, momentum, shape] if clean_text(line))


def _condition_fit_display(condition_fit: Mapping[str, Any]) -> str:
    mark = clean_text(condition_fit.get("mark"))
    label = clean_text(condition_fit.get("label"))
    reason = clean_text(condition_fit.get("reason"))
    if not mark and not label and not reason:
        return ""
    head = f"{mark}{label}" if mark else f"—{label or '条件実績なし'}"
    return f"条件実績 {head}" + (f" / {reason}" if reason else "")


def _trend_display(value: Any) -> str:
    text = clean_text(value)
    if not text:
        return ""
    if _contains_any(text, UP_TREND_WORDS):
        return f"↗{text}"
    if _contains_any(text, DOWN_TREND_WORDS):
        return f"↘{text}"
    return f"→{text}"


def _front_survival_flag(*values: Any) -> bool | None:
    text = " ".join(clean_text(value) for value in values if clean_text(value))
    if not text:
        return None
    if any(style in text for style in FRONT_STYLE_WORDS) and _contains_any(text, PACE_SUPPORT_WORDS):
        return True
    if _contains_any(text, ("後方", "展開不向き", "課題")):
        return False
    return None


def _race_comment_role(row: Mapping[str, Any], *values: Any) -> str | None:
    roles = [
        _pick(row, "展開印", "pace_mark"),
        _pick(row, "展開タイプ"),
        *values,
    ]
    text = " / ".join(clean_text(value) for value in roles if clean_text(value))
    return text or None


def _start_group_from_style(style: Any) -> str | None:
    text = clean_text(style)
    if not text:
        return None
    if "逃" in text or "先" in text:
        return "前方"
    if "差" in text:
        return "中団"
    if "追" in text:
        return "後方"
    return None


def _trend_label(row: Mapping[str, Any], trend: Any) -> Any:
    return _pick(row, "状態", "form_state", "勢い", "勢いランク", "momentum_rank") or trend


def _gauge_from_existing_ability(value: Any) -> int | None:
    number = to_float(value)
    if number is None:
        return None
    return int(round(max(0.0, min(100.0, number))))


def _unique_numbers(values: Iterable[Any]) -> list[str]:
    return unique_nums(horse_no(value) for value in values)


def _number(row: Mapping[str, Any], *names: str) -> float | None:
    return to_float(_pick(row, *names))


def _pick(row: Mapping[str, Any], *names: str) -> Any:
    for name in names:
        if name not in row:
            continue
        value = row.get(name)
        if not _missing(value):
            return value
    return None


def _none_if_empty(value: Any) -> Any:
    return None if _missing(value) else value


def _missing(value: Any) -> bool:
    if value is None:
        return True
    try:
        if pd.isna(value):
            return True
    except (TypeError, ValueError):
        pass
    return clean_text(value).lower() in {"", "-", "—", "nan", "none", "null", "データなし", "未取得"}


def _contains_any(text: Any, words: Iterable[str]) -> bool:
    value = clean_text(text)
    return any(word in value for word in words)
